config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :infos
  root to: "infos#index"

end

app/models/info.rb
class Info < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/infos_controller.rb
class InfosController < ApplicationController
  before_action :set_info, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /infos
  # GET /infos.json
  def index
    @infos = Info.all
  end

  # GET /infos/1
  # GET /infos/1.json
  def show
  end

  # GET /infos/new
  def new
    @info = Info.new
  end

  # GET /infos/1/edit
  def edit
  end

  # POST /infos
  # POST /infos.json
  def create
    @info = Info.new(info_params)

    respond_to do |format|
      if @info.save
        format.html { redirect_to @info, notice: 'Info was successfully created.' }
        format.json { render :show, status: :created, location: @info }
      else
        format.html { render :new }
        format.json { render json: @info.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /infos/1
  # PATCH/PUT /infos/1.json
  def update
    respond_to do |format|
      if @info.update(info_params)
        format.html { redirect_to @info, notice: 'Info was successfully updated.' }
        format.json { render :show, status: :ok, location: @info }
      else
        format.html { render :edit }
        format.json { render json: @info.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /infos/1
  # DELETE /infos/1.json
  def destroy
    @info.destroy
    respond_to do |format|
      format.html { redirect_to infos_url, notice: 'Info was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_info
      @info = Info.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def info_params
      params.require(:info).permit(:name, :birth_date, :gender, :register_id, :location)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/infos_helper.rb
module InfosHelper
end

app/views/infos/_form.html.erb
<%= form_for(@info) do |f| %>
  <% if @info.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@info.errors.count, "error") %> prohibited this info from being saved:</h2>

      <ul>
      <% @info.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :birth_date %><br>
    <%= f.number_field :birth_date %>
  </div>
  <div class="field">
    <%= f.label :gender %><br>
    <%= f.text_field :gender %>
  </div>
  <div class="field">
    <%= f.label :register_id %><br>
    <%= f.text_area :register_id %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/infos/edit.html.erb
<h1>Editing Info</h1>

<%= render 'form' %>

<%= link_to 'Show', @info %> |
<%= link_to 'Back', infos_path %>

app/views/infos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Infos</h1>
<% if user_signed_in? %>
<li>
  <%= link_to('logout',destroy_user_session_path, :method => :delete) %>
</li>
<% else %>
<%= link_to('login',user_session_path) %>
<% end %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Birth date</th>
      <th>Gender</th>
      <th>Register</th>
      <th>Location</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @infos.each do |info| %>
      <tr>
        <td><%= info.name %></td>
        <td><%= info.birth_date %></td>
        <td><%= info.gender %></td>
        <td><%= info.register_id %></td>
        <td><%= info.location %></td>
        <td><%= link_to 'Show', info %></td>
        <td><%= link_to 'Edit', edit_info_path(info) %></td>
        <td><%= link_to 'Destroy', info, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Info', new_info_path %>

app/views/infos/new.html.erb
<h1>New Info</h1>

<%= render 'form' %>

<%= link_to 'Back', infos_path %>

app/views/infos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @info.name %>
</p>

<p>
  <strong>Birth date:</strong>
  <%= @info.birth_date %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @info.gender %>
</p>

<p>
  <strong>Register:</strong>
  <%= @info.register_id %>
</p>

<p>
  <strong>Location:</strong>
  <%= @info.location %>
</p>

<%= link_to 'Edit', edit_info_path(@info) %> |
<%= link_to 'Back', infos_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<html>
<head>
  <title>Temka12</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>